-- ELIMINAR LAS FK Y TABLAS

ALTER TABLE dbo.Game DROP CONSTRAINT FK_Game_User;
ALTER TABLE dbo.Game DROP CONSTRAINT FK_Game_QUIZZ;
ALTER TABLE dbo.Game DROP CONSTRAINT FK_Game_RPG;
ALTER TABLE dbo.Game DROP CONSTRAINT FK_Game_DECISIONES;
ALTER TABLE dbo.Answer DROP CONSTRAINT FK_Answer_Question;
ALTER TABLE dbo.[User] DROP CONSTRAINT FK_User_Avatar;
ALTER TABLE dbo.[User] DROP CONSTRAINT FK_User_UserInfo;
ALTER TABLE dbo.UserTask DROP CONSTRAINT FK_UserTask_User;
ALTER TABLE dbo.Log DROP CONSTRAINT FK_Log_User;
ALTER TABLE dbo.Log DROP CONSTRAINT FK_Log_Activity;
ALTER TABLE dbo.Log DROP CONSTRAINT FK_Log_Answer;

DROP TABLE IF EXISTS Avatar;
DROP TABLE IF EXISTS QUIZZ;
DROP TABLE IF EXISTS RPG;
DROP TABLE IF EXISTS DECISIONES;
DROP TABLE IF EXISTS Game;
DROP TABLE IF EXISTS Question;
DROP TABLE IF EXISTS Answer;
DROP TABLE IF EXISTS Activity;
DROP TABLE IF EXISTS Log;
DROP TABLE IF EXISTS UserInfo;
DROP TABLE IF EXISTS UserTask;
DROP TABLE IF EXISTS [User];